version: build-{build}

branches:
  only:
  - master

configuration: Release

platform: x64

clone_depth: 1

clone_folder: c:\projects\dcm2niix

init:
- ps: >-
    $version = Get-Date -Format "d-MMM-yyyy"

    $githash = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)

    Update-AppveyorBuild -Version "$version-$githash"

before_build:
- cmd: >-
    echo "Clone yaml-cpp"

    git clone -q --depth=1 --branch=master https://github.com/jbeder/yaml-cpp.git c:\projects\dcm2niix\yaml-cpp

    echo "Running cmake"

    mkdir c:\projects\dcm2niix\build

    cd c:\projects\dcm2niix\build

    cmake -G "Visual Studio 14 2015 Win64" -DBATCH_VERSION=ON -Wno-dev ..\

build:
  project: c:\projects\dcm2niix\build\dcm2niix.sln

  verbosity: normal

after_build:
- ps: >-
    cd c:\projects\dcm2niix

    7z a dcm2niix-$version-win.zip c:\projects\dcm2niix\bin\Release\* >$null

artifacts:
  - path: 'dcm2niix-*.zip'
    name: dcm2niix
